# Capstone Project - The Battle of Neighborhoods

## Finding places to build a students apartment in Berlin

### Author: Sijie Cheng

#### 1. Introduction

according to statistik from study.eu, that over 150,000 students made the choice to study in Berlin, of which 15% are from abroad.

For international student, one of challenges when they moving into Berlin is to find a suitable accommodation, and a student apartment, which runs by a qualified housing company, is most reliable choice. **Therefor in this project, explore different neighborhoods of Berlin and find the best suitable place to build a student apartment are the main tasks.**

Considering simplicity and practical of this project, **only the safety and general atmosphere of the neighborhood** are take into consideration.

#### 2. Data acquisition

#### a. Daten zum Kriminalitätsatlas 2012-2018 (crime data 2012-2018)

* Berlin crime records by boroughs from 2012 to 2018.

* Source: https://www.kriminalitaetsatlas.berlin.de/K-Atlas/atlas.html

In [1]:
import pandas as pd
import numpy as np

In [14]:
crime_path = r"C:\Users\camch\Desktop\Coursera_Capstone\Fallzahlen&HZ 2012-2018.xlsx"
crime = pd.read_excel(crime_path, sheet_name='Fallzahlen_2018')
crime.head()

# the 1st and 2nd column (Bezirksregion) means district region
# the 3rd column (Straftaten insgesamt) means the total number of crime
# the other columns is the types of crime

,LOR-Schlüssel (Bezirksregion),Bezeichnung (Bezirksregion),Straftaten \n-insgesamt-,Raub,1,Körper-verletzungen \n-insgesamt-,Gefährl. und schwere Körper-verletzung,"Freiheits-beraubung, Nötigung,\nBedrohung, Nachstellung",Diebstahl \n-insgesamt-,Diebstahl von Kraftwagen,Diebstahl \nan/aus Kfz,Fahrrad-\ndiebstahl,Wohnraum\n-einbruch,Branddelikte \n-insgesamt-,Brand-\nstiftung,Sach-beschädigung -insgesamt-,Sach-beschädigung durch Graffiti,Rauschgif-tdelikte,Kieztaten
0,10111,Tiergarten Süd,5171,70,58,416,125,103,2540,17,274,310,39,14,3,284,42,273,1247
1,10112,Regierungsviertel,9146,34,16,519,110,114,3883,15,199,372,35,6,1,407,159,133,857
2,10113,Alexanderplatz,19275,130,80,1531,366,309,10144,68,580,880,133,26,6,1036,333,971,2798
3,10114,Brunnenstraße Süd,4207,26,14,286,60,69,1817,47,153,314,56,9,6,442,218,69,690
4,10221,Moabit West,7257,71,38,653,164,215,2470,37,398,447,83,29,12,496,99,435,1262

In [15]:
# translate
crime_columns = ['Borough_Nu', 'Borough', 'Total', 'Robbery', 'Street_Robbery', 'Body_Harm_Total', 'Serious_Body_Harm', 'Threat', 'Theft_Total', 'Theft_Motor', 'Theft_Vehicles', 'Theft_Bicycle', 'Burglary', 'Arson_Total', 'Arson', 'Property_Damage_Total', 'Property_Damage', 'Drug', 'Others']
crime.columns = crime_columns

In [16]:
crime

,Borough_Nu,Borough,Total,Robbery,Street_Robbery,Body_Harm_Total,Serious_Body_Harm,Threat,Theft_Total,Theft_Motor,Theft_Vehicles,Theft_Bicycle,Burglary,Arson_Total,Arson,Property_Damage_Total,Property_Damage,Drug,Others
0,10111,Tiergarten Süd,5171,70,58,416,125,103,2540,17,274,310,39,14,3,284,42,273,1247
1,10112,Regierungsviertel,9146,34,16,519,110,114,3883,15,199,372,35,6,1,407,159,133,857
2,10113,Alexanderplatz,19275,130,80,1531,366,309,10144,68,580,880,133,26,6,1036,333,971,2798
3,10114,Brunnenstraße Süd,4207,26,14,286,60,69,1817,47,153,314,56,9,6,442,218,69,690
4,10221,Moabit West,7257,71,38,653,164,215,2470,37,398,447,83,29,12,496,99,435,1262
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,123012,Nord 2 - Waidmannslust/Wittenau/Lübars,3074,25,11,375,98,144,1168,35,168,132,97,11,3,311,83,95,765
146,123021,MV 1 - Märkisches Viertel,3125,44,22,464,101,184,1135,76,257,69,34,30,8,269,15,95,918
147,123022,MV 2 - Rollbergsiedlung,859,5,2,102,21,51,298,7,54,24,19,2,0,107,29,18,204
148,123043,West 3 - Borsigwalde/Freie Scholle,1135,6,3,94,21,50,506,28,121,59,55,4,3,136,32,18,267
149,129900,"Bezirk (Rd), nicht zuzuordnen",1571,12,10,100,21,38,736,12,136,52,1,5,2,63,2,33,213

In [17]:
crime.shape

(150, 19)

In [18]:
# delete unnecessary columns
crime.drop(crime.columns[3:19], axis=1, inplace=True)
crime.drop(crime.columns[0], axis=1, inplace=True)
crime

                                    Borough  Total
0                            Tiergarten Süd   5171
1                         Regierungsviertel   9146
2                            Alexanderplatz  19275
3                         Brunnenstraße Süd   4207
4                               Moabit West   7257
..                                      ...    ...
145  Nord 2 - Waidmannslust/Wittenau/Lübars   3074
146               MV 1 - Märkisches Viertel   3125
147                 MV 2 - Rollbergsiedlung    859
148      West 3 - Borsigwalde/Freie Scholle   1135
149           Bezirk (Rd), nicht zuzuordnen   1571

[150 rows x 2 columns]

#### b. List of Berlin boroughs

* Scrapping data of neighborhoods from Wikipedia
* source: https://de.wikipedia.org/wiki/Verwaltungsgliederung_Berlins

#### c. Foursquare

* Using Foursquare API to get venues data

#### 3. Methodology

based on crime data and Berlin boroughs data, to analysis and visualise the total number of crime and ratio of crime to population. Then use Foursquare to get the most common venues and use K-mean clustering to group borough into at least 5 cluster. Finally based on the characterics of each cluster and crime raio, choose 1 or 2 boroughs that suits to build a student apartment based on safety and atomosphere.